# Copyright (c) 2021 Nordic Semiconductor ASA
# SPDX-License-Identifier: Apache-2.0

manifest:
  self:
    west-commands: scripts/west-commands.yml

  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
    - name: nrfconnect
      url-base: https://github.com/nrfconnect
    - name: IntergatedCircuits
      url-base: https://github.com/IntergatedCircuits

  projects:
    - name: c2usb
      remote: IntergatedCircuits
      revision: 891665bb540bca0abf84910bef3fa4946bf6d26b
      clone-depth: 1
    - name: nrf
      repo-path: sdk-nrf
      remote: nrfconnect
      revision: v2.9.0
      clone-depth: 1
      import:
        # By using name-allowlist we can clone only the modules that are
        # strictly needed by the application.
        name-allowlist:
          - zephyr
          - cmsis
          - hal_nordic
          - nrfxlib
          - tinycrypt
